
import React, { useState, useRef } from 'react';
import { Plus, Edit2, Trash2, Check, X, Download, Upload, MonitorSmartphone, AlertCircle, ShieldCheck } from 'lucide-react';
import { Category, TransactionType, Transaction, PatientDailyStat, BalanceItem, AppTheme } from '../types';
import * as XLSX from 'xlsx';

interface CategoriesProps {
  categories: Category[];
  transactions: Transaction[];
  patientStats: PatientDailyStat[];
  balanceItems: BalanceItem[];
  theme: AppTheme;
  onAdd: (name: string, type: TransactionType) => void;
  onUpdate: (id: string, name: string) => void;
  onDelete: (id: string) => void;
  onImport: (data: any) => void;
}

export const Categories: React.FC<CategoriesProps> = ({ 
  categories, transactions, patientStats, balanceItems, theme, onAdd, onUpdate, onDelete, onImport 
}) => {
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editName, setEditName] = useState('');
  const [newName, setNewName] = useState('');
  const [newType, setNewType] = useState<TransactionType>('Income');
  const fileInputRef = useRef<HTMLInputElement>(null);

  // EXPORT KE EXCEL (XLSX) MULTI-SHEET
  const exportBackupXLSX = () => {
    const wb = XLSX.utils.book_new();

    // Sheet 1: Transactions
    const wsTransactions = XLSX.utils.json_to_sheet(transactions);
    XLSX.utils.book_append_sheet(wb, wsTransactions, "Transactions");

    // Sheet 2: Categories
    const wsCategories = XLSX.utils.json_to_sheet(categories);
    XLSX.utils.book_append_sheet(wb, wsCategories, "Categories");

    // Sheet 3: PatientStats
    const wsPatientStats = XLSX.utils.json_to_sheet(patientStats);
    XLSX.utils.book_append_sheet(wb, wsPatientStats, "DailyStats");

    // Sheet 4: BalanceItems
    const wsBalance = XLSX.utils.json_to_sheet(balanceItems);
    XLSX.utils.book_append_sheet(wb, wsBalance, "BalanceItems");

    // Sheet 5: Theme & Settings (Single Row)
    const wsSettings = XLSX.utils.json_to_sheet([theme]);
    XLSX.utils.book_append_sheet(wb, wsSettings, "Settings");

    // Write File
    XLSX.writeFile(wb, `Full_Backup_Basmalah_${new Date().toISOString().split('T')[0]}.xlsx`);
  };

  // IMPORT DARI EXCEL (XLSX) MULTI-SHEET
  const handleImportXLSX = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      if (!window.confirm("PERINGATAN: Tindakan ini akan MENIMPA SELURUH DATA aplikasi dengan data dari file Excel. Lanjutkan?")) {
        event.target.value = '';
        return;
      }

      const reader = new FileReader();
      reader.onload = (e) => {
        try {
          const data = e.target?.result;
          const workbook = XLSX.read(data, { type: 'array' });
          
          const restoredData: any = {};

          // Helper to safely get sheet data
          const getSheetData = (sheetName: string) => {
            const sheet = workbook.Sheets[sheetName];
            return sheet ? XLSX.utils.sheet_to_json(sheet) : [];
          };

          restoredData.transactions = getSheetData("Transactions");
          restoredData.categories = getSheetData("Categories");
          restoredData.patientStats = getSheetData("DailyStats");
          restoredData.balanceItems = getSheetData("BalanceItems");
          
          const settingsArr = getSheetData("Settings");
          if (settingsArr.length > 0) {
            restoredData.theme = settingsArr[0];
          }

          onImport(restoredData);
          alert("Data berhasil dipulihkan dari file Excel!");
          window.location.reload(); 
        } catch (err) {
          console.error(err);
          alert("Gagal membaca file Excel Backup. Pastikan format file benar (Multi-sheet generated by system).");
        }
      };
      reader.readAsArrayBuffer(file);
    }
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-500 pb-10">
      
      {/* BOX MIGRASI DATA */}
      <div className="bg-indigo-600 rounded-[2.5rem] p-10 text-white shadow-2xl relative overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full -mr-32 -mt-32 blur-3xl" />
        <div className="relative z-10 flex flex-col lg:flex-row items-center justify-between gap-8">
          <div className="flex items-center gap-6">
            <div className="p-5 bg-white/20 backdrop-blur-md rounded-3xl">
              <MonitorSmartphone className="w-10 h-10 text-white" />
            </div>
            <div>
              <h3 className="text-2xl font-black mb-1">Backup & Restore (Excel)</h3>
              <p className="text-indigo-100 text-sm max-w-md">Data disimpan dalam file Excel (.xlsx) dengan multiple sheets. Mudah dibaca dan aman untuk dicadangkan.</p>
            </div>
          </div>
          <div className="flex flex-wrap gap-4">
            <button 
              onClick={exportBackupXLSX}
              className="bg-white text-indigo-600 px-8 py-4 rounded-2xl font-black text-sm flex items-center gap-2 hover:bg-indigo-50 transition-all shadow-xl active:scale-95"
            >
              <Download className="w-5 h-5" /> UNDUH BACKUP (.XLSX)
            </button>
            <button 
              onClick={() => fileInputRef.current?.click()}
              className="bg-indigo-950 text-white px-8 py-4 rounded-2xl font-black text-sm flex items-center gap-2 hover:bg-black transition-all shadow-xl active:scale-95"
            >
              <Upload className="w-5 h-5" /> RESTORE DARI EXCEL
            </button>
            <input type="file" ref={fileInputRef} className="hidden" accept=".xlsx" onChange={handleImportXLSX} />
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="bg-emerald-50 border border-emerald-100 p-6 rounded-3xl flex items-center gap-4">
          <ShieldCheck className="w-8 h-8 text-emerald-600" />
          <div>
            <p className="text-xs font-black text-emerald-800 uppercase tracking-widest">Keamanan Data</p>
            <p className="text-xs text-emerald-600">File Excel tersimpan lokal di komputer Anda. Tidak ada data yang dikirim ke cloud.</p>
          </div>
        </div>
        <div className="bg-amber-50 border border-amber-100 p-6 rounded-3xl flex items-center gap-4">
          <AlertCircle className="w-8 h-8 text-amber-600" />
          <div>
            <p className="text-xs font-black text-amber-800 uppercase tracking-widest">Struktur Excel</p>
            <p className="text-xs text-amber-600">Jangan mengubah nama Sheet (Transactions, Categories, dll) agar proses Restore berjalan lancar.</p>
          </div>
        </div>
      </div>

      {/* MANAJEMEN KATEGORI */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <CategoryList 
          title="Kategori Pendapatan" 
          type="Income" 
          categories={categories.filter(c => c.type === 'Income')} 
          onAdd={onAdd} onUpdate={onUpdate} onDelete={onDelete} 
          editingId={editingId} setEditingId={setEditingId} editName={editName} setEditName={setEditName}
          newName={newName} setNewName={setNewName}
        />
        <CategoryList 
          title="Kategori Pengeluaran" 
          type="Expense" 
          categories={categories.filter(c => c.type === 'Expense')} 
          onAdd={onAdd} onUpdate={onUpdate} onDelete={onDelete} 
          editingId={editingId} setEditingId={setEditingId} editName={editName} setEditName={setEditName}
          newName={newName} setNewName={setNewName}
        />
      </div>
    </div>
  );
};

const CategoryList: React.FC<any> = ({ title, type, categories, onAdd, onUpdate, onDelete, editingId, setEditingId, editName, setEditName, newName, setNewName }) => {
  return (
    <div className="bg-white p-8 rounded-[2rem] border border-slate-200 shadow-sm">
      <h3 className="text-lg font-black text-slate-800 mb-6 uppercase tracking-widest">{title}</h3>
      <div className="flex gap-2 mb-8">
        <input 
          type="text" 
          placeholder="Tambah kategori baru..."
          className="flex-1 bg-slate-50 border-2 border-transparent focus:border-indigo-500/20 focus:bg-white rounded-2xl px-5 py-4 outline-none font-bold transition-all"
          value={newName}
          onChange={(e) => setNewName(e.target.value)}
        />
        <button 
          onClick={() => { onAdd(newName, type); setNewName(''); }}
          className="bg-indigo-600 text-white p-4 rounded-2xl hover:bg-indigo-700 shadow-lg"
        >
          <Plus className="w-6 h-6" />
        </button>
      </div>
      <div className="space-y-2">
        {categories.map((cat: any) => (
          <div key={cat.id} className="flex items-center justify-between p-4 bg-slate-50 rounded-2xl group hover:bg-white hover:shadow-md transition-all">
            {editingId === cat.id ? (
              <input 
                autoFocus
                className="flex-1 bg-white border-b-2 border-indigo-500 font-bold outline-none"
                value={editName}
                onChange={(e) => setEditName(e.target.value)}
                onBlur={() => { onUpdate(cat.id, editName); setEditingId(null); }}
              />
            ) : (
              <span className="font-bold text-slate-700">{cat.name}</span>
            )}
            <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
              <button onClick={() => { setEditingId(cat.id); setEditName(cat.name); }} className="p-2 text-slate-400 hover:text-indigo-600"><Edit2 className="w-4 h-4" /></button>
              <button onClick={() => onDelete(cat.id)} className="p-2 text-slate-400 hover:text-rose-600"><Trash2 className="w-4 h-4" /></button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
